let a = 'hello';
let b = 'owu';
let c = 'com';
let d = 'ua';
let i = 1;
let f = 10;
let g = -999;
let m = 123;
let l = 3.14;
let k = 2.7;
let s = 16;
let v = 'true';
let w = 'false';
console.log(a);
console.log(b);
console.log(c);
console.log(d);
console.log(i);
console.log(f);
console.log(g);
console.log(m);
console.log(l);
console.log(k);
console.log(s);
console.log(v);
console.log(w);